import Head from 'next/head'
import React, { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import Header from '../../components/Header'
import Login from '../../components/Login'
import { handlePlayQuiz } from '../../slices/playIdSlice'
import { addNextQuizzes } from '../../slices/nextQuizzes'
import { addPlayersLeaderboard } from '../../slices/playersLeaderboard'

const Play = ({ request, nextQuizzes }) => {
  const dispatch = useDispatch()
  useEffect(() => {
    if (request) dispatch(handlePlayQuiz(request))
    if (nextQuizzes) dispatch(addNextQuizzes(nextQuizzes))
  }, [request])

  return (
    <div className="bg-[#233237] w-full h-screen z-50 bg-login bg-cover bg-no-repeat">
      <Head>
        <title>Team Space X | Play</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Login nextQuizzes={nextQuizzes} />
    </div>
  )
}

export default Play

export const getServerSideProps = async ({ query }) => {
  const request = await (
    await fetch(`https://localhost:7104/admin/Quizzes/${query.id}`, {
      rejectUnauthorized: false,
      method: 'GET',
      cache: 'no-cache',
    })
  ).json()
  const nextQuizzes = await (
    await fetch('https://localhost:7104/admin/Quizzes', {
      rejectUnauthorized: false,
      method: 'GET',
      cache: 'no-cache',
    })
  ).json()
  // const leaderboard = await (
  //   await fetch(
  //     ` https://localhost:7104/admin/Quizzes/FinishQuiz/${query.id}`,
  //     {
  //       rejectUnauthorized: false,
  //       method: 'POST',
  //     }
  //   )
  // ).json()
  return {
    props: {
      request,
      nextQuizzes,
      // leaderboard,
    },
  }
}
