import Head from 'next/head'
import React from 'react'
import CreateQuizComponent from '../../components/CreateQuizComponent'
import Header from '../../components/Header'
import ImageModal from '../../components/ImageModal'
import Error from '../../components/Error'

const CreateQuiz = () => {
  return (
    <div>
      <Head>
        <title>Trivia Game | Create Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CreateQuizComponent />
      <ImageModal />
      <Error />
    </div>
  )
}

export default CreateQuiz
