import Head from 'next/head'
import AdminQuestionComponent from '../../components/AdminQuestionComponent'
import { useEffect } from 'react'
import Error from '../../components/Error'
import Header from '../../components/Header'
import { useDispatch } from 'react-redux'
import { addquizById } from '../../slices/quizById'

const AdminId = ({ request }) => {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(addquizById(request))
  }, [request])

  return (
    <div>
      <Head>
        <title>Trivia Game | {request.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AdminQuestionComponent />
      <Error />
    </div>
  )
}

export default AdminId

export const getServerSideProps = async ({ query }) => {
  const request = await (
    await fetch(`https://localhost:7104/admin/Quizzes/${query.id}`, {
      rejectUnauthorized: false,
      method: 'GET',
      cache: 'no-cache',
    })
  ).json()
  return {
    props: {
      request,
    },
  }
}
