import Head from 'next/head'
import React, { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import Error from '../../components/Error'
import Header from '../../components/Header'
import MyQuizzes from '../../components/MyQuizes'
import PastQuizes from '../../components/PastQuizes'
import { addCurrentQuizzes } from '../../slices/currentQuizzes'
import { addPastQuizzes } from '../../slices/pastQuizzes'

const Admin = ({ getNextQuizzes, getPastQuizzes }) => {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(addCurrentQuizzes(getNextQuizzes))
    dispatch(addPastQuizzes(getPastQuizzes))
  }, [getNextQuizzes])
  return (
    <div>
      <Head>
        <title>Trivia Game | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MyQuizzes />
      <PastQuizes />
      <Error />
    </div>
  )
}

export default Admin

export const getServerSideProps = async () => {
  const getNextQuizzes = await (
    await fetch('https://localhost:7104/admin/Quizzes', {
      rejectUnauthorized: false,
      method: 'GET',
      cache: 'no-cache',
    })
  ).json()
  const getPastQuizzes = await (
    await fetch('https://localhost:7104/admin/Quizzes/GetPastQuizzes', {
      rejectUnauthorized: false,
      method: 'GET',
      cache: 'no-cache',
    })
  ).json()
  return {
    props: {
      getNextQuizzes,
      getPastQuizzes,
    },
  }
}
