// <auto-generated />
using System;
using HQTrivia.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HQTrivia.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230202120411_RemovedCurrencyTypeFromQuiz")]
    partial class RemovedCurrencyTypeFromQuiz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HQTrivia.Models.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Earth"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Mars"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Mercury"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Neptune"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Neil Armstrong"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Lance Armstrong"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Buzz Lightyear"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Buzz Aldrin"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Jupiter"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Venus"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Mars"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Pluto"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Erwin Hubble"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Albert Hubble"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Christopher Hubble"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Edwin Hubble"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Earth"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Mercury"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Saturn"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Pluto"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Mercury"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Saturn"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Uranus"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Jupiter"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Uranus"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Jupiter"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Saturn"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Neptune"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Apollo 1"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Apollo 3"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Apollo 11"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Apollo 13"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "3"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "1"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "4"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "6"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Voids"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Bolts"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Death Valley"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Black holes"
                        });
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Which of these planets has rings?"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Who was the first person to step foot on the moon?"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Exploration Rovers investigated which planet between 2004 and 2018?"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Who is the Hubble Space Telescope named after?"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Which planet is located between Venus and Mars?"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Which of these planets has the shortest year?"
                        },
                        new
                        {
                            Id = 7,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Which planet has 9 continuous rings?"
                        },
                        new
                        {
                            Id = 8,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "The first manned space mission to land on the Moon was called what?"
                        },
                        new
                        {
                            Id = 9,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "How many planets in our solar system are larger than Earth?"
                        },
                        new
                        {
                            Id = 10,
                            Duration = 10,
                            IsSent = false,
                            QuizId = 1,
                            Text = "Vast empty space with little or no galaxies can be found are known as which of these?"
                        });
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ThumbNailURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2023, 2, 2, 13, 4, 11, 394, DateTimeKind.Local).AddTicks(4170),
                            Name = "Space",
                            Prize = "1000",
                            StartingDateTime = new DateTime(2023, 12, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            ThumbNailURL = "https://www.travelandleisure.com/thmb/sH4T0ElWwZFyUhtqAZD3USeiaSc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/james-webb-hole-WEBB0722-a7b14258290d4da9be4c7d50ee732d9b.jpg"
                        });
                });

            modelBuilder.Entity("HQTrivia.Models.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Answer", b =>
                {
                    b.HasOne("HQTrivia.Models.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Question", b =>
                {
                    b.HasOne("HQTrivia.Models.Models.Quiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizId");
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("HQTrivia.Models.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
